[package]
name = "penrose-config"
version = "0.1.0"
authors = ["YohananDiamond <mitonanan12@gmail.com>"]
edition = "2018"

[dependencies]
penrose = { git = "https://github.com/sminez/penrose", branch = "develop" }
simplelog = "0.8.0"

[[bin]]
name = "penrose-main"
path = "src/main.rs"
